### ISSUE TITLE
Min, Max, and Average are stored incorrectly

### ISSUE THREAD

**Issue by jamilgafur** [jamilgafur/heuristic_convex_optimization_code#10]
I have tried debugging this myself and can not seem to find the problem.

### **On "error_checking" branch:**

GSA lines: 146 - 161 error likely in here

            smallest = min([particle.cost for particle in self.swarm])
            self.min_results.append(smallest)
            largest = max([particle.cost for particle in self.swarm])
            self.max_results.append(largest)
            self.avg.append((smallest+largest)/self.num_particles)
            self.std.append(statistics.stdev([particle.cost for particle in self.swarm ]))
            print("\tBest individual seen fitness value: {:0.3f}".format(self.best_cost))
            output_dictionary = {"iterations": [i for i in range(1, self.maxiter+1)], "max": self.max_results, "avg": self.avg, "min": 
            self.min_results, "std": self.std}
            return self.best_cost_location, self.costFunc(self.best_cost_location), output_dictionary

Inside the jupyter notebook when you print out the min, max, and average of the GSA the arrays are not corresponding with what we send in. 

    Given the code:
        print(GSAfiles[0])
        GSA_data = pd.read_csv(GSAfiles[0])
        print(GSA_data["Min"])
        print(GSA_data["Average"])
        print(GSA_data["Max"])

the output is:

```GSA_iteration_10_pop_30_k_1_n_1_seed_1234_single.csv
0    0.148912
1    0.148473
2    0.145559
3    0.132836
4    0.113373
5    0.094446
6    0.089033
7    0.082035
8    0.081973
9    0.079119
Name: Min, dtype: float64
0    2.926993
1    2.903221
2    2.890898
3    2.889692
4    2.888609
5    2.878518
6    2.851832
7    2.830021
8    2.829698
9    2.829338
Name: Average, dtype: float64
0    0.102530
1    0.101723
2    0.101215
3    0.100751
4    0.100066
5    0.099099
6    0.098029
7    0.097069
8    0.097056
9    0.096949
Name: Max, dtype: float64
```

where the average is the max values, the max is the min values and the min is the average values

**Comment by 14corman** [comment]
I am not sure why you think your error is in 146-161. In your GSA code, you are getting max and min values from your cost matrix. 146-161 deals with updating the best_so_far. You want to see where your cost matrix is getting updated.

Also, the lines of code you post above are not in your GSA. Why are you using different methods of getting max and min from what is in your GSA code? In your GSA code you use cost matrix to get max and min, and above you are using the particles in the swarm.

On another note, can you use the range to find average? You are not summing over all particles but instead adding max and min and dividing by number of particles. Is that a good way to find average?

Lastly, is this only happening for GSA, or is it happening for every algorithm?

**Comment by jamilgafur** [comment]
I updated the code to be more modular for distributed processing later on.

for the line(s)
```
largest = max([particle.cost for particle in self.swarm])
self.max_results.append(largest)
```
I am getting the particle with the largest cost, and adding it to the list, max_results, which holds the largest cost. When you print out this list and compare it to the CSV it is swapped.

**Comment by jamilgafur** [comment]
@14corman  you are correct, the error is in the save_csv_single function and it is breaking for the PSO and GSA functions. I cant seem to figure out where the problem is though
